# Análisis de inasistencias

Inasistencias por programa, sede, semestre, módulo, grupo y seguimiento.

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/inasistencias_enriquecido.csv")

print(f"Total registros: {len(df):,}")
print(f"Estudiantes únicos: {df['Numero_identificacion_estudiante'].nunique():,}")
print(f"Módulos: {df['Nombre_modulo'].nunique()}")
print(f"Sedes: {df['Sede'].nunique()}")
print(f"Programas: {df['Nombre_programa_limpio'].nunique()}")

Total registros: 23,178
Estudiantes únicos: 1,023
Módulos: 66
Sedes: 5
Programas: 5

In [3]:
tabla_programa = df.groupby(["Nombre_programa_limpio", "Sede", "Nombre_nivel"]).agg(
    Total_estudiantes=("Numero_identificacion_estudiante", "nunique"),
    Total_inasistencias=("Cantidad_inasistencia", "sum"),
    Promedio_inasistencias=("Cantidad_inasistencia", "mean")
).reset_index().round(1).sort_values("Promedio_inasistencias", ascending=False).reset_index(drop=True)

display(tabla_programa)

,Nombre_programa_limpio,Sede,Nombre_nivel,Total_estudiantes,Total_inasistencias,Promedio_inasistencias
0,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,BASTIDAS,Semestre 01,35,27379,13.7
1,TECNOLOGÍA EN MARKETING DIGITAL,BASTIDAS,Semestre 01,29,13704,12.9
2,TECNOLOGÍA EN MARKETING DIGITAL,MINCA,Semestre 02,19,6802,10.2
3,TECNOLOGÍA EN MARKETING DIGITAL,BURITACA,Semestre 02,20,4465,9.4
4,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,PESCAITO,Semestre 01,45,9760,7.9
5,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,INEM,Semestre 01,60,10162,7.3
6,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,INEM,Semestre 02,31,5269,7.1
7,TECNOLOGÍA EN MARKETING DIGITAL,PESCAITO,Semestre 01,42,7417,7.0
8,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,MINCA,Semestre 02,18,3200,6.8
9,TECNOLOGÍA EN GESTIÓN DE SERVICIOS GASTRONÓMICOS,INEM,Semestre 01,110,18371,6.7
10,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,BURITACA,Semestre 02,32,3960,6.4
11,TECNOLOGÍA EN MARKETING DIGITAL,INEM,Semestre 02,29,3007,5.9
12,TECNOLOGÍA EN GESTIÓN DE SERVICIOS GASTRONÓMICOS,INEM,Semestre 02,36,5029,5.7
13,TECNOLOGÍA EN MARKETING DIGITAL,INEM,Semestre 01,77,7603,5.6
14,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,INEM,Semestre 02,28,2092,5.1
15,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,INEM,Semestre 01,83,6045,4.8
16,TECNOLOGÍA EN GESTIÓN DE PRODUCCIÓN DE MODAS,INEM,Semestre 01,58,2516,4.5
17,TECNOLOGÍA EN MARKETING DIGITAL,BURITACA,Semestre 01,16,421,4.1
18,TECNOLOGÍA EN MARKETING DIGITAL,MINCA,Semestre 01,8,373,4.1
19,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,MINCA,Semestre 01,7,87,2.6
20,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,BURITACA,Semestre 01,9,115,2.2

In [4]:
tabla_modulo = df.groupby(["Nombre_modulo", "Nombre_programa_limpio"]).agg(
    Total_estudiantes=("Numero_identificacion_estudiante", "nunique"),
    Total_inasistencias=("Cantidad_inasistencia", "sum"),
    Promedio_inasistencias=("Cantidad_inasistencia", "mean")
).reset_index().round(1).sort_values("Promedio_inasistencias", ascending=False).reset_index(drop=True)

display(tabla_modulo)

,Nombre_modulo,Nombre_programa_limpio,Total_estudiantes,Total_inasistencias,Promedio_inasistencias
0,HERRAMIENTAS TICS,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,146,15299,14.3
1,INGLÉS I,TECNOLOGÍA EN MARKETING DIGITAL,167,12894,12.0
2,GESTIÓN DE PRECIOS Y PERCEPCIÓN DE VALOR,TECNOLOGÍA EN MARKETING DIGITAL,63,3080,9.7
3,SEO Y SEM POSICIONAMIENTO WEB,TECNOLOGÍA EN MARKETING DIGITAL,47,1923,8.9
4,GESTIÓN NAVIERA Y PORTUARIA,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,148,5212,8.8
...,...,...,...,...,...
58,INFRAESTRUCTURA PORTUARIA,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,16,56,2.2
59,LECTOESCRITURA Y COMUNICACIÓN TÉCNICA,TECNOLOGÍA EN GESTIÓN DE PRODUCCIÓN DE MODAS,26,59,1.6
60,COMPETENCIAS HUMANAS Y DESARROLLO INTEGRAL,TECNOLOGÍA EN GESTIÓN DE PRODUCCIÓN DE MODAS,24,51,1.5
61,PROBABILIDAD Y ESTADÍSTICA,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,1,1,1.0
62,PATRONAJE Y ESCALADO,TECNOLOGÍA EN GESTIÓN DE PRODUCCIÓN DE MODAS,13,13,1.0

In [5]:
tabla_seguimiento = df.groupby(["Seguimiento", "Grupo", "Nombre_programa_limpio"]).agg(
    Total_estudiantes=("Numero_identificacion_estudiante", "nunique"),
    Total_inasistencias=("Cantidad_inasistencia", "sum"),
    Promedio_inasistencias=("Cantidad_inasistencia", "mean")
).reset_index().round(1).sort_values("Promedio_inasistencias", ascending=False).reset_index(drop=True)

display(tabla_seguimiento)

,Seguimiento,Grupo,Nombre_programa_limpio,Total_estudiantes,Total_inasistencias,Promedio_inasistencias
0,Seguimiento 1 (01 Feb – 01 Abr),A,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,194,20214,9.5
1,Seguimiento 1 (06 Abr – 09 May),B,TECNOLOGÍA EN MARKETING DIGITAL,56,3991,9.4
2,Seguimiento 2 (02 Abr – 13 May),A,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,194,19565,9.3
3,Seguimiento 3 (14 May – 25 Jun),A,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,194,8674,8.7
4,Seguimiento 2 (02 Abr – 13 May),A,TECNOLOGÍA EN MARKETING DIGITAL,171,12155,8.2
5,Seguimiento 1 (01 Feb – 01 Abr),A,TECNOLOGÍA EN MARKETING DIGITAL,177,14128,8.0
6,Seguimiento 2 (10 May – 13 Jun),B,TECNOLOGÍA EN MARKETING DIGITAL,53,2792,7.8
7,Seguimiento 3 (14 May – 25 Jun),A,TECNOLOGÍA EN MARKETING DIGITAL,165,5448,7.5
8,Seguimiento 3 (14 May – 25 Jun),A,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,81,1988,7.2
9,Seguimiento 2 (02 Abr – 13 May),A,TECNOLOGÍA EN GESTIÓN DE SERVICIOS GASTRONÓMICOS,140,8908,7.1
10,Seguimiento 1 (06 Abr – 09 May),B,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,62,2050,7.0
11,Seguimiento 3 (14 May – 25 Jun),A,TECNOLOGÍA EN GESTIÓN DE SERVICIOS GASTRONÓMICOS,136,3818,7.0
12,Seguimiento 2 (02 Abr – 13 May),A,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,88,4906,6.9
13,Seguimiento 1 (01 Feb – 01 Abr),A,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,88,5360,6.6
14,Seguimiento 2 (10 May – 13 Jun),B,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,63,1448,6.5
15,Seguimiento 1 (06 Abr – 09 May),B,TECNOLOGÍA EN GESTIÓN DE PRODUCCIÓN DE MODAS,34,868,6.0
16,Seguimiento 1 (01 Feb – 01 Abr),A,TECNOLOGÍA EN GESTIÓN DE SERVICIOS GASTRONÓMICOS,146,10674,5.8
17,Seguimiento 2 (10 May – 13 Jun),B,TECNOLOGÍA EN GESTIÓN DE PRODUCCIÓN DE MODAS,56,1648,4.0

In [6]:
print("=== TOP 10 MÓDULOS CON MAYOR PROMEDIO DE INASISTENCIAS ===")
display(tabla_modulo.head(10))

=== TOP 10 MÓDULOS CON MAYOR PROMEDIO DE INASISTENCIAS ===

,Nombre_modulo,Nombre_programa_limpio,Total_estudiantes,Total_inasistencias,Promedio_inasistencias
0,HERRAMIENTAS TICS,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,146,15299,14.3
1,INGLÉS I,TECNOLOGÍA EN MARKETING DIGITAL,167,12894,12.0
2,GESTIÓN DE PRECIOS Y PERCEPCIÓN DE VALOR,TECNOLOGÍA EN MARKETING DIGITAL,63,3080,9.7
3,SEO Y SEM POSICIONAMIENTO WEB,TECNOLOGÍA EN MARKETING DIGITAL,47,1923,8.9
4,GESTIÓN NAVIERA Y PORTUARIA,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,148,5212,8.8
5,EXPRESIÓN ORAL Y ARGUMENTACIÓN,TECNOLOGÍA EN MARKETING DIGITAL,50,1934,8.7
6,RAZONAMIENTO CUANTITATIVO,TECNOLOGÍA EN GESTIÓN DE OPERACIONES LOGÍSTICAS,133,5514,8.7
7,INGLÉS II,TECNOLOGÍA EN MARKETING DIGITAL,61,2600,8.6
8,ETIQUETA Y PROTOCOLO EN SERVICIOS TURÍSTICOS,TECNOLOGÍA EN GESTIÓN DEL TURISMO CULTURAL Y D...,43,1682,8.6
9,RAZONAMIENTO CUANTITATIVO,TECNOLOGÍA EN GESTIÓN DE SERVICIOS GASTRONÓMICOS,44,1627,8.5

In [7]:
print("=== INASISTENCIAS POR SEDE ===")
tabla_sede = df.groupby("Sede").agg(
    Total_estudiantes=("Numero_identificacion_estudiante", "nunique"),
    Total_inasistencias=("Cantidad_inasistencia", "sum"),
    Promedio_inasistencias=("Cantidad_inasistencia", "mean")
).reset_index().round(1).sort_values("Promedio_inasistencias", ascending=False).reset_index(drop=True)

display(tabla_sede)

=== INASISTENCIAS POR SEDE ===

       Sede  Total_estudiantes  Total_inasistencias  Promedio_inasistencias
0  BASTIDAS                 64                41083                    13.4
1     MINCA                 52                10462                     8.3
2  PESCAITO                 87                17177                     7.5
3  BURITACA                 77                 8961                     7.2
4      INEM                512                60094                     6.1

In [9]:
df.columns

Index(['Numero_identificacion_estudiante', 'Nombre_completo_estudiante',
       'Sexo', 'Correo_electronico', 'Celular', 'Codigo_curso', 'Nombre_curso',
       'Codigo_modulo', 'Nombre_modulo', 'Horario_curso', 'Periodo_curso',
       'Numero_identificacion_docente', 'Nombre_docente',
       'Cantidad_inasistencia', 'Dia', 'Fecha_inasistencia', 'Hora',
       'Justificacion', 'Detalle_justificacion', 'Numero_identificacion',
       'Nombre_programa_limpio', 'Sede', 'Nombre_nivel', 'Grupo',
       'Seguimiento'],
      dtype='str')

In [ ]:
tabla_inasitencia_por_asignatura_ = df.groupby(['Nombre_completo_estudiante', 'Nombre_modulo','Seguimiento' ]).agg(
    Inasistencias_Totales=("Numero_identificacion_estudiante", "count"),
    Promedio_inasistencias=("Cantidad_inasistencia", "mean")
).reset_index().round(1).sort_values("Promedio_inasistencias", ascending=False).reset_index(drop=True)

display(tabla_modulo)

,Nombre_completo_estudiante,Nombre_modulo,Seguimiento,Inasistencias_Totales,Promedio_inasistencias
0,Ana Paola Guzman Montes,HERRAMIENTAS TICS,Seguimiento 2 (02 Abr – 13 May),12,32.0
1,Ana Paola Guzman Montes,HERRAMIENTAS TICS,Seguimiento 1 (01 Feb – 01 Abr),16,32.0
2,Ana Paola Guzman Montes,HERRAMIENTAS TICS,Seguimiento 3 (14 May – 25 Jun),4,32.0
3,Mariana Margarita Guzman Montes,INGLÉS I,Seguimiento 1 (01 Feb – 01 Abr),16,32.0
4,Meira Alejandra arias Camacho,HERRAMIENTAS TICS,Seguimiento 2 (02 Abr – 13 May),12,32.0
...,...,...,...,...,...
9109,Talia Lorena Rico Mejia,INTRODUCCIÓN AL COMERCIO EXTERIOR,Seguimiento 3 (14 May – 25 Jun),1,1.0
9110,Tatiana Marcela Rodríguez Bolaño,INTRODUCCIÓN AL MARKETING DIGITAL,Seguimiento 1 (01 Feb – 01 Abr),1,1.0
9111,Tatiana Marcela Rodríguez Bolaño,ÉTICA PROFESIONAL EN LOS NEGOCIOS,Seguimiento 2 (02 Abr – 13 May),1,1.0
9112,ADRIAN CAMILO BAUTISTA BABILONIA,INGLÉS TÉCNICO II,Seguimiento 2 (02 Abr – 13 May),1,1.0
9113,ADRIAN CAMILO BAUTISTA BABILONIA,FORMACIÓN EN CULTURA CIUDADANA,Seguimiento 2 (02 Abr – 13 May),1,1.0